<a href="https://colab.research.google.com/github/Nur9702/Sertifkat_submission/blob/main/Jigar_seryozipred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.1)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.1.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)

In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [3]:
# malumot apisini yuklab olish
!kaggle competitions download -c multiclassificationtask

In [4]:
!ls

kaggle.json  multiclassificationtask.zip  sample_data

In [5]:
from zipfile import ZipFile
dataset = "/content/multiclassificationtask.zip"
with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print('Done')

Done

In [6]:
!ls

kaggle.json  multiclassificationtask.zip  sample_data  sample_submission.csv  test.csv	train.csv

In [7]:
!pip install py7zr

Collecting py7zr
  Downloading py7zr-0.22.0-py3-none-any.whl.metadata (16 kB)
Collecting texttable (from py7zr)
  Downloading texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting pycryptodomex>=3.16.0 (from py7zr)
  Downloading pycryptodomex-3.22.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting pyzstd>=0.15.9 (from py7zr)
  Downloading pyzstd-0.16.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.4 kB)
Collecting pyppmd<1.2.0,>=1.1.0 (from py7zr)
  Downloading pyppmd-1.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting pybcj<1.1.0,>=1.0.0 (from py7zr)
  Downloading pybcj-1.0.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting multivolumefile>=0.2.3 (from py7zr)
  Downloading multivolumefile-0.2.3-py3-none-any.whl.metadata (6.3 kB)
Collecting inflate64<1.1.0,>=1.0.0 (from py7zr)
  Downloading inflate64-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting brotli>=1.1.0 (from py7zr)
  Downloading Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from py7zr) (5.9.5)
Downloading py7zr-0.22.0-py3-none-any.whl (67 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 kB 2.8 MB/s eta 0:00:00
Downloading Brotli-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 39.7 MB/s eta 0:00:00
Downloading inflate64-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 kB 8.2 MB/s eta 0:00:00
Downloading multivolumefile-0.2.3-py3-none-any.whl (17 kB)
Downloading pybcj-1.0.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 4.3 MB/s eta 0:00:00
Downloading pycryptodomex-3.22.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 78.0 MB/s eta 0:00:00
Downloading pyppmd-1.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.3/141.3 kB 12.6 MB/s eta 0:00:00
Downloading pyzstd-0.16.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (413 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.7/413.7 kB 30.0 MB/s eta 0:00:00
Downloading texttable-1.7.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: texttable, brotli, pyzstd, pyppmd, pycryptodomex, pybcj, multivolumefile, inflate64, py7zr
Successfully installed brotli-1.1.0 inflate64-1.0.1 multivolumefile-0.2.3 py7zr-0.22.0 pybcj-1.0.3 pycryptodomex-3.22.0 pyppmd-1.1.1 pyzstd-0.16.2 texttable-1.7.0

In [8]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [9]:
!binarymulticlassificationtask_path = kagglehub.competition_download('multiclassificationtask')

/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `binarymulticlassificationtask_path = kagglehub.competition_download('multiclassificationtask')'

In [10]:

# Get the current working directory
current_directory = os.getcwd()
print("Current working directory:", current_directory)

# List files in the current directory
print("Files in current directory:", os.listdir(current_directory))


# Assuming the dataset was extracted to the current working directory
train_file_path = os.path.join(current_directory, 'train.csv')
test_file_path = os.path.join(current_directory, 'test.csv')
submission_file_path = os.path.join(current_directory, 'sample_submission.csv')
# Load the data, handling potential errors
try:
    train = pd.read_csv(train_file_path, index_col='id')
    test = pd.read_csv(test_file_path, index_col='id')
    submission = pd.read_csv(submission_file_path)
    print("Data loaded successfully.")
except FileNotFoundError:
    print(f"Error: File not found at {train_file_path}")
    print("Please make sure the dataset is extracted to the correct location.")
# Display the first few rows of the training data
train.head()

Current working directory: /content
Files in current directory: ['.config', 'multiclassificationtask.zip', 'kaggle.json', 'sample_submission.csv', 'test.csv', 'train.csv', 'sample_data']
Data loaded successfully.

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
id,,,,,,,,,,,,,,,,,,,
0,2178.0,D-penicillamine,16374.0,F,N,N,N,N,0.5,263.0,3.20,43.0,1110.0,106.95,67.0,430.0,9.6,3.0,C
1,2644.0,D-penicillamine,17774.0,F,N,N,N,N,0.8,280.0,3.60,22.0,678.0,62.00,80.0,427.0,13.0,3.0,C
2,3069.0,Placebo,17844.0,F,N,N,N,N,1.1,408.0,4.40,54.0,2108.0,142.60,137.0,203.0,10.6,3.0,C
3,2216.0,Placebo,19221.0,F,N,Y,Y,N,0.8,252.0,3.70,36.0,843.0,55.80,56.0,336.0,9.6,4.0,C
4,2256.0,Placebo,21600.0,F,N,N,N,N,4.7,348.0,3.06,464.0,961.0,120.90,146.0,298.0,11.0,2.0,D

In [11]:
train.isnull().sum()

N_Days              0
Drug             6506
Age                 0
Sex                 0
Ascites          6498
Hepatomegaly     6508
Spiders          6509
Edema               0
Bilirubin           0
Cholesterol      8299
Albumin             0
Copper           6601
Alk_Phos         6512
SGOT             6514
Tryglicerides    8334
Platelets         564
Prothrombin        16
Stage               0
Status              0
dtype: int64

In [12]:
len(train)

15000

In [13]:
#duplikatlarni olib tashemiz
train.duplicated().sum()
train.drop_duplicates(inplace=True)

In [14]:
train.duplicated().sum()

np.int64(0)

In [15]:
test.duplicated().sum()
test.drop_duplicates(inplace=True)
test.duplicated().sum()

np.int64(0)

In [16]:
submission.duplicated().sum()
submission.drop_duplicates(inplace=True)
submission.duplicated().sum()

np.int64(0)

In [17]:
train.isnull().sum()

N_Days              0
Drug             6500
Age                 0
Sex                 0
Ascites          6492
Hepatomegaly     6502
Spiders          6503
Edema               0
Bilirubin           0
Cholesterol      8293
Albumin             0
Copper           6595
Alk_Phos         6506
SGOT             6508
Tryglicerides    8328
Platelets         564
Prothrombin        16
Stage               0
Status              0
dtype: int64

In [19]:
#train1 = train.drop(['Cholesterol', 'Tryglicerides'], axis=1)

train.head()

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
id,,,,,,,,,,,,,,,,,,,
0,2178.0,D-penicillamine,16374.0,F,N,N,N,N,0.5,263.0,3.20,43.0,1110.0,106.95,67.0,430.0,9.6,3.0,C
1,2644.0,D-penicillamine,17774.0,F,N,N,N,N,0.8,280.0,3.60,22.0,678.0,62.00,80.0,427.0,13.0,3.0,C
2,3069.0,Placebo,17844.0,F,N,N,N,N,1.1,408.0,4.40,54.0,2108.0,142.60,137.0,203.0,10.6,3.0,C
3,2216.0,Placebo,19221.0,F,N,Y,Y,N,0.8,252.0,3.70,36.0,843.0,55.80,56.0,336.0,9.6,4.0,C
4,2256.0,Placebo,21600.0,F,N,N,N,N,4.7,348.0,3.06,464.0,961.0,120.90,146.0,298.0,11.0,2.0,D

In [20]:
train.isnull().sum()

N_Days              0
Drug             6500
Age                 0
Sex                 0
Ascites          6492
Hepatomegaly     6502
Spiders          6503
Edema               0
Bilirubin           0
Cholesterol      8293
Albumin             0
Copper           6595
Alk_Phos         6506
SGOT             6508
Tryglicerides    8328
Platelets         564
Prothrombin        16
Stage               0
Status              0
dtype: int64

In [21]:
# Calculate the mean of each numerical column, ignoring NaNs
column_means = train.select_dtypes(include=np.number).mean()

# Fill missing values with the calculated means
train1 = train.fillna(column_means)

In [22]:
train.isnull().sum()

N_Days              0
Drug             6500
Age                 0
Sex                 0
Ascites          6492
Hepatomegaly     6502
Spiders          6503
Edema               0
Bilirubin           0
Cholesterol      8293
Albumin             0
Copper           6595
Alk_Phos         6506
SGOT             6508
Tryglicerides    8328
Platelets         564
Prothrombin        16
Stage               0
Status              0
dtype: int64

In [23]:
train['N_Days'].value_counts()

N_Days
2537.0    158
2149.0    145
597.0     130
1097.0    129
2563.0    125
         ...
1658.0      1
1378.0      1
2656.0      1
1490.0      1
4239.0      1
Name: count, Length: 553, dtype: int64

In [24]:
train['Ascites'].value_counts()

Ascites
N    8116
Y     386
Name: count, dtype: int64

In [25]:
train['Hepatomegaly'].value_counts()

Hepatomegaly
N    4634
Y    3858
Name: count, dtype: int64

In [26]:
train['Spiders'].value_counts()

Spiders
N    6769
Y    1722
Name: count, dtype: int64

In [27]:
# Filling with most_frequent method
train['Drug'].fillna(train1['Drug'].mode()[0], inplace=True)

<ipython-input-27-48db9d8372da>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['Drug'].fillna(train1['Drug'].mode()[0], inplace=True)

In [28]:
train.fillna(method='ffill', inplace=True)

<ipython-input-28-e6f994489f06>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  train.fillna(method='ffill', inplace=True)

In [29]:
train.isnull().sum()

N_Days           0
Drug             0
Age              0
Sex              0
Ascites          0
Hepatomegaly     0
Spiders          0
Edema            0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
Status           0
dtype: int64

In [30]:
test1 = test.drop(['Cholesterol', 'Tryglicerides'], axis=1)

test1.head()

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Albumin,Copper,Alk_Phos,SGOT,Platelets,Prothrombin,Stage
id,,,,,,,,,,,,,,,,
15000,22646.0,NaN,22646.0,F,NaN,NaN,NaN,N,1.4,3.34,NaN,NaN,NaN,190.0,11.0,4.0
15001,2149.0,NaN,18993.0,F,NaN,NaN,NaN,N,0.9,3.24,NaN,NaN,NaN,233.0,9.0,2.0
15002,3850.0,D-penicillamine,16050.0,M,N,N,N,N,1.0,3.64,75.0,2148.0,102.3,172.0,10.6,3.0
15003,2419.0,D-penicillamine,20354.0,F,N,N,N,N,0.6,3.96,31.0,642.0,70.0,336.0,10.8,2.0
15004,1086.0,NaN,23376.0,F,NaN,NaN,NaN,N,4.4,4.40,NaN,NaN,NaN,447.0,10.3,2.0

In [31]:
# Filling with most_frequent method
test1['Drug'].fillna(test1['Drug'].mode()[0], inplace=True)

<ipython-input-31-fac5122b7101>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test1['Drug'].fillna(test1['Drug'].mode()[0], inplace=True)

In [32]:
test1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9996 entries, 15000 to 24999
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   N_Days        9996 non-null   float64
 1   Drug          9996 non-null   object
 2   Age           9996 non-null   float64
 3   Sex           9996 non-null   object
 4   Ascites       5609 non-null   object
 5   Hepatomegaly  5598 non-null   object
 6   Spiders       5596 non-null   object
 7   Edema         9996 non-null   object
 8   Bilirubin     9996 non-null   float64
 9   Albumin       9996 non-null   float64
 10  Copper        5531 non-null   float64
 11  Alk_Phos      5597 non-null   float64
 12  SGOT          5594 non-null   float64
 13  Platelets     9614 non-null   float64
 14  Prothrombin   9987 non-null   float64
 15  Stage         9996 non-null   float64
dtypes: float64(10), object(6)
memory usage: 1.3+ MB

In [33]:
len(test1)

9996

In [34]:
test1['Drug'].value_counts()

Drug
D-penicillamine    7420
Placebo            2576
Name: count, dtype: int64

In [35]:
test1.head()

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Albumin,Copper,Alk_Phos,SGOT,Platelets,Prothrombin,Stage
id,,,,,,,,,,,,,,,,
15000,22646.0,D-penicillamine,22646.0,F,NaN,NaN,NaN,N,1.4,3.34,NaN,NaN,NaN,190.0,11.0,4.0
15001,2149.0,D-penicillamine,18993.0,F,NaN,NaN,NaN,N,0.9,3.24,NaN,NaN,NaN,233.0,9.0,2.0
15002,3850.0,D-penicillamine,16050.0,M,N,N,N,N,1.0,3.64,75.0,2148.0,102.3,172.0,10.6,3.0
15003,2419.0,D-penicillamine,20354.0,F,N,N,N,N,0.6,3.96,31.0,642.0,70.0,336.0,10.8,2.0
15004,1086.0,D-penicillamine,23376.0,F,NaN,NaN,NaN,N,4.4,4.40,NaN,NaN,NaN,447.0,10.3,2.0

In [36]:
test1['Ascites'].fillna(method='bfill', inplace=True)

<ipython-input-36-68ce4b065c45>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test1['Ascites'].fillna(method='bfill', inplace=True)
<ipython-input-36-68ce4b065c45>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test1['Ascites'].fillna(method='bfill', inplace=True)

In [37]:
test1['Hepatomegaly'].fillna(method='bfill', inplace=True)

<ipython-input-37-dede2c936df4>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test1['Hepatomegaly'].fillna(method='bfill', inplace=True)
<ipython-input-37-dede2c936df4>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test1['Hepatomegaly'].fillna(method='bfill', inplace=True)

In [38]:
test1.isnull().sum()

N_Days             0
Drug               0
Age                0
Sex                0
Ascites            1
Hepatomegaly       1
Spiders         4400
Edema              0
Bilirubin          0
Albumin            0
Copper          4465
Alk_Phos        4399
SGOT            4402
Platelets        382
Prothrombin        9
Stage              0
dtype: int64

In [39]:
test1.fillna(method='bfill', inplace=True)

<ipython-input-39-4ebc351b2014>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test1.fillna(method='bfill', inplace=True)

In [40]:
test1.fillna(method='ffill', inplace=True)

<ipython-input-40-cc586b300981>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test1.fillna(method='ffill', inplace=True)

In [42]:
#test1['Spiders'] = pd.to_numeric(test1['Spiders'], errors='coerce')
#test1['Spiders'].fillna(test1['Spiders'].mean(), inplace=True)

#test1['Spiders'].fillna(0, inplace=True)

<ipython-input-42-df7a11655ee3>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test1['Spiders'].fillna(test1['Spiders'].mean(), inplace=True)
<ipython-input-42-df7a11655ee3>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test1['Spiders'].fillna(0, inplace=True)

In [41]:
test1.isnull().sum()

N_Days          0
Drug            0
Age             0
Sex             0
Ascites         0
Hepatomegaly    0
Spiders         0
Edema           0
Bilirubin       0
Albumin         0
Copper          0
Alk_Phos        0
SGOT            0
Platelets       0
Prothrombin     0
Stage           0
dtype: int64

In [42]:
submission.isnull().sum()

id           0
Status_C     0
Status_CL    0
Status_D     0
dtype: int64

In [45]:
train.head()

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
id,,,,,,,,,,,,,,,,,,,
0,2178.0,D-penicillamine,16374.0,F,N,N,N,N,0.5,263.0,3.20,43.0,1110.0,106.95,67.0,430.0,9.6,3.0,C
1,2644.0,D-penicillamine,17774.0,F,N,N,N,N,0.8,280.0,3.60,22.0,678.0,62.00,80.0,427.0,13.0,3.0,C
2,3069.0,Placebo,17844.0,F,N,N,N,N,1.1,408.0,4.40,54.0,2108.0,142.60,137.0,203.0,10.6,3.0,C
3,2216.0,Placebo,19221.0,F,N,Y,Y,N,0.8,252.0,3.70,36.0,843.0,55.80,56.0,336.0,9.6,4.0,C
4,2256.0,Placebo,21600.0,F,N,N,N,N,4.7,348.0,3.06,464.0,961.0,120.90,146.0,298.0,11.0,2.0,D

In [67]:
# onehot encoder I need
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='if_binary') # drop='if_binary' added

# Perform one-hot encoding for categorical features EXCLUDING 'Status'
categorical_features = ['Drug', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema']

# Check for empty columns in train1 before encoding:
for feature in categorical_features:
    if train[feature].empty:
        print(f"Column '{feature}' is empty!")
        # Handle empty columns (e.g., remove or impute values)

# Fit the encoder and transform the categorical features
encoded_data = encoder.fit_transform(train[categorical_features])

# Get feature names from the encoder
feature_names = encoder.get_feature_names_out(categorical_features)

# Create a DataFrame from the encoded data
train_encoded_df = pd.DataFrame(encoded_data, columns=feature_names, index=train1.index)

# Concatenate the encoded features with the original DataFrame and 'Status' column
train_encoded = pd.concat([train1, train_encoded_df, train1[['Status']]], axis=1)

# Drop original categorical features (excluding 'Status')
train_encoded = train_encoded.drop(categorical_features, axis=1)
train_encoded.sample(15)

,N_Days,Age,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,...,Status,Drug_Placebo,Sex_M,Ascites_Y,Hepatomegaly_Y,Spiders_Y,Edema_N,Edema_S,Edema_Y,Status
id,,,,,,,,,,,,,,,,,,,,,
1014,1216.0,15105.0,6.4,586.000000,3.61,95.000000,2115.000000,141.050000,134.000000,318.0,...,C,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,C
59,2365.0,16300.0,0.8,267.000000,3.54,30.000000,688.000000,57.000000,85.000000,201.0,...,C,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C
4575,2475.0,17703.0,1.2,460.000000,3.70,148.000000,1472.000000,108.500000,118.000000,335.0,...,C,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C
7780,1741.0,23107.0,0.5,328.000000,3.69,37.000000,7277.000000,98.000000,98.000000,358.0,...,C,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C
8764,1925.0,25011.0,0.9,329.177302,3.65,75.647339,1618.598233,106.483631,111.387886,224.0,...,C,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,C
4892,1223.0,16071.0,0.9,329.177302,3.68,75.647339,1618.598233,106.483631,111.387886,209.0,...,C,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,C
13726,1067.0,15037.0,2.3,375.000000,3.34,18.000000,1258.000000,179.800000,111.387886,378.0,...,CL,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,CL
7102,4190.0,14060.0,0.6,132.000000,3.80,13.000000,423.000000,49.600000,58.000000,265.0,...,C,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C
14527,1097.0,21185.0,2.8,329.177302,3.75,75.647339,1618.598233,106.483631,111.387886,244.0,...,C,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C
1788,2224.0,14754.0,0.6,373.000000,3.61,44.000000,1282.000000,122.450000,104.000000,156.0,...,C,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C
6372,2563.0,20089.0,0.7,329.177302,4.01,75.647339,1618.598233,106.483631,111.387886,388.0,...,C,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C
4297,1783.0,14684.0,0.5,251.000000,3.70,59.000000,724.000000,125.550000,56.000000,281.0,...,C,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C
4069,3059.0,14060.0,0.9,248.000000,3.20,32.000000,661.000000,57.000000,90.000000,248.0,...,C,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,C
10719,264.0,15857.0,8.5,329.177302,3.48,161.000000,1428.000000,181.350000,111.387886,102.0,...,D,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,D
14563,1095.0,19237.0,2.7,329.177302,3.14,75.647339,1618.598233,106.483631,111.387886,475.0,...,C,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,C

In [47]:
# Instead of:
test1.fillna(method='ffill', inplace=True)

<ipython-input-47-d2b18f7ed2e5>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  test1.fillna(method='ffill', inplace=True)

In [48]:
test1.head()

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Albumin,Copper,Alk_Phos,SGOT,Platelets,Prothrombin,Stage
id,,,,,,,,,,,,,,,,
15000,22646.0,D-penicillamine,22646.0,F,N,N,N,N,1.4,3.34,75.0,2148.0,102.30,190.0,11.0,4.0
15001,2149.0,D-penicillamine,18993.0,F,N,N,N,N,0.9,3.24,75.0,2148.0,102.30,233.0,9.0,2.0
15002,3850.0,D-penicillamine,16050.0,M,N,N,N,N,1.0,3.64,75.0,2148.0,102.30,172.0,10.6,3.0
15003,2419.0,D-penicillamine,20354.0,F,N,N,N,N,0.6,3.96,31.0,642.0,70.00,336.0,10.8,2.0
15004,1086.0,D-penicillamine,23376.0,F,N,Y,Y,N,4.4,4.40,121.0,6121.8,56.76,447.0,10.3,2.0

In [49]:
test1['Drug'].value_counts()

Drug
D-penicillamine    7420
Placebo            2576
Name: count, dtype: int64

In [50]:
test1.isnull().values.any()

np.False_

In [51]:
test1.sample(15)

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Albumin,Copper,Alk_Phos,SGOT,Platelets,Prothrombin,Stage
id,,,,,,,,,,,,,,,,
20204,1030.0,Placebo,22960.0,F,N,N,N,N,1.1,3.99,96.0,1293.0,91.00,422.0,9.9,2.0
18250,1250.0,D-penicillamine,11058.0,F,N,N,N,N,2.2,3.60,39.0,2148.0,102.30,344.0,10.0,3.0
17279,597.0,D-penicillamine,23376.0,F,N,N,N,N,2.3,3.34,22.0,1024.0,77.50,224.0,10.4,2.0
23990,3086.0,Placebo,20535.0,F,N,N,N,N,0.9,3.97,38.0,1629.0,141.05,277.0,10.5,2.0
24627,597.0,D-penicillamine,19724.0,F,N,Y,N,S,1.4,3.75,161.0,674.0,26.35,224.0,12.3,3.0
16373,489.0,D-penicillamine,21915.0,F,N,N,N,N,0.4,3.60,20.0,666.0,54.25,280.0,10.6,3.0
22280,3090.0,D-penicillamine,22977.0,F,N,Y,N,N,8.5,3.87,201.0,2424.0,201.50,216.0,10.7,3.0
19649,1347.0,D-penicillamine,22280.0,F,N,N,N,N,1.6,3.76,143.0,1472.0,188.34,142.0,10.6,4.0
20362,2272.0,D-penicillamine,22642.0,F,N,N,N,N,0.5,4.08,29.0,622.0,66.65,206.0,10.0,3.0
23268,2574.0,D-penicillamine,19567.0,F,N,N,Y,N,0.6,3.95,36.0,310.0,83.70,371.0,11.0,4.0
21384,1328.0,D-penicillamine,23376.0,F,N,Y,N,N,0.5,3.15,84.0,1857.0,299.15,269.0,10.1,4.0
21100,1592.0,Placebo,13995.0,F,N,N,N,N,5.1,4.17,84.0,1345.0,147.25,207.0,10.0,3.0
17883,1790.0,Placebo,19994.0,F,N,Y,N,N,0.6,3.35,34.0,1868.0,170.50,166.0,11.0,4.0
16448,3231.0,D-penicillamine,25202.0,M,N,N,N,N,0.8,3.58,94.0,6456.2,106.95,269.0,11.0,3.0
15364,249.0,D-penicillamine,22336.0,F,N,N,N,N,1.9,3.78,17.0,1828.0,71.30,125.0,10.0,2.0

In [52]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Assuming test1 are your DataFrames

# List of categorical features to encode
categorical_features = ['Drug', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders', 'Edema']

# Create a OneHotEncoder instance
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='if_binary') # drop='if_binary' added for efficiency

# Fit the encoder on the training data
encoder.fit(test1[categorical_features]) # Fit using the training data (test1)

# Transform both training and testing data
test1_encoded = encoder.transform(test1[categorical_features])

# Get feature names from the encoder
feature_names = encoder.get_feature_names_out(categorical_features)

# Create DataFrames from the encoded data
test1_encoded_df = pd.DataFrame(test1_encoded, columns=feature_names, index=test1.index)

# Concatenate the encoded features with the original DataFrames
test1 = pd.concat([test1, test1_encoded_df], axis=1)

# Drop the original categorical columns
test1.drop(categorical_features, axis=1, inplace=True)

In [53]:
test1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9996 entries, 15000 to 24999
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   N_Days          9996 non-null   float64
 1   Age             9996 non-null   float64
 2   Bilirubin       9996 non-null   float64
 3   Albumin         9996 non-null   float64
 4   Copper          9996 non-null   float64
 5   Alk_Phos        9996 non-null   float64
 6   SGOT            9996 non-null   float64
 7   Platelets       9996 non-null   float64
 8   Prothrombin     9996 non-null   float64
 9   Stage           9996 non-null   float64
 10  Drug_Placebo    9996 non-null   float64
 11  Sex_M           9996 non-null   float64
 12  Ascites_Y       9996 non-null   float64
 13  Hepatomegaly_Y  9996 non-null   float64
 14  Spiders_Y       9996 non-null   float64
 15  Edema_N         9996 non-null   float64
 16  Edema_S         9996 non-null   float64
 17  Edema_Y         9996 non-null   float64
dtypes: float64(18)
memory usage: 1.4 MB

In [54]:
test1.sample(15)

,N_Days,Age,Bilirubin,Albumin,Copper,Alk_Phos,SGOT,Platelets,Prothrombin,Stage,Drug_Placebo,Sex_M,Ascites_Y,Hepatomegaly_Y,Spiders_Y,Edema_N,Edema_S,Edema_Y
id,,,,,,,,,,,,,,,,,,
15498,3992.0,14245.0,0.8,3.00,36.0,1080.0,106.95,226.0,10.8,3.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
24917,2580.0,25569.0,0.9,3.81,13.0,1082.0,55.80,265.0,10.0,4.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
16581,2176.0,17263.0,6.3,3.48,75.0,2176.0,170.50,236.0,10.6,2.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
18290,2221.0,22642.0,0.5,3.10,68.0,6456.2,54.25,270.0,10.6,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
24585,1103.0,17046.0,3.3,3.34,57.0,1273.0,119.35,401.0,11.0,4.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
19128,4500.0,19994.0,1.1,3.77,94.0,1009.0,151.90,283.0,11.0,4.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
20785,1478.0,16071.0,0.9,2.58,63.0,676.0,99.33,214.0,10.3,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
23904,3255.0,16109.0,1.0,3.20,52.0,1074.0,110.05,181.0,10.8,4.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17622,2168.0,26580.0,0.7,3.60,20.0,1087.0,128.65,427.0,9.9,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
24595,1223.0,16071.0,0.7,3.94,13.0,1622.0,85.25,256.0,10.6,4.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
23725,1295.0,16513.0,1.1,4.09,22.0,642.0,74.40,176.0,9.6,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
23872,1746.0,19724.0,1.6,3.63,63.0,1087.0,79.05,286.0,10.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
20191,1328.0,23376.0,0.9,3.60,67.0,1105.0,137.95,246.0,10.8,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
23524,2855.0,19358.0,1.8,3.26,65.0,746.0,74.40,330.0,9.9,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19552,1847.0,24107.0,1.8,3.40,88.0,810.0,163.00,331.0,11.0,4.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0

In [71]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 1. Convert train1_encoded to a DataFrame if it's a NumPy array
train1_encoded = pd.DataFrame(train_encoded)

# 2. Separate features (X) and target (y)
X = train_encoded.drop('Status', axis=1)  # Features (all columns except 'Status')
y = train_encoded['Status'].iloc[:, 0]  # Select the first 'Status' column

# 3. Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# 4. Create and train the model
model = RandomForestClassifier(random_state=42)  # You can customize hyperparameters
model.fit(X_train, y_train)

# 5. Make predictions on the test set
y_pred = model.predict(X_test)

# 6. Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# 7. Align test data columns with training data columns
# Get missing columns in test1
missing_cols = set(X_train.columns) - set(test1.columns)

# Add missing columns to test1 with fill value 0
for c in missing_cols:
    test1[c] = 0

# Ensure order of column is the same as in X_train
test1 = test1[X_train.columns]

# 8. Predict probabilities on new data (e.g., your 'test1' DataFrame)
test_probabilities = model.predict_proba(test1) # Get probabilities for each class

# 9. Get the class with the highest probability
test_predictions = [model.classes_[i] for i in np.argmax(test_probabilities, axis=1)] #changed to get the classes based on highest probability
#print("Qatorlar ehtimolligi:\n", test_probabilities)
proba_df = pd.DataFrame(test_probabilities, columns=model.classes_, index=test1.index)
columns_1 = [col for col in proba_df.columns if col != 'Y']

print("Qatorlar ehtimolligi:\n", proba_df[columns_1].sample(15))  # Display first few rows

Accuracy: 0.8522840946982327
Qatorlar ehtimolligi:
           C    CL     D
id
15179  0.97  0.02  0.01
18841  0.32  0.04  0.64
17197  0.16  0.10  0.74
22505  0.24  0.05  0.71
23130  0.98  0.01  0.01
23023  0.17  0.00  0.83
17924  0.28  0.03  0.69
23621  0.42  0.05  0.53
18362  0.24  0.04  0.72
21833  0.55  0.08  0.37
15399  0.05  0.11  0.84
17060  0.75  0.14  0.11
24230  0.72  0.01  0.27
17758  0.47  0.04  0.49
23676  0.73  0.02  0.25

In [72]:
# Submissionga saqlash
submission = submission[submission['id'].isin(test1.index)]  # Filter submission to match test1 index
submission['Status'] = test_predictions # Now assign the predictions
submission.to_csv('submission.csv', index=False)